# Generated by Django 3.2.8 on 2021-10-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211012_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Societa',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('codice_fiscale', models.CharField(max_length=11)),
                ('denominazione', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=200)),
            ],
        ),
    ]
