# Generated by Django 3.2.8 on 2021-10-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_societa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBacheca',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('data', models.DateField()),
                ('percorso', models.CharField(max_length=200)),
            ],
        ),
    ]
