# Generated by Django 3.2.8 on 2021-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_documentobacheca'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobacheca',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
