# Generated by Django 3.2.8 on 2021-10-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_documentobacheca_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentobacheca',
            old_name='url',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='documentobacheca',
            name='percorso',
        ),
    ]
