# Generated by Django 3.2.8 on 2021-10-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_documentobacheca_permessi'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobacheca',
            name='nome',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
