# Generated by Django 3.2.8 on 2021-10-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_documentobacheca_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scadenziario',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('protocollo', models.CharField(max_length=200)),
                ('titolo', models.CharField(max_length=200)),
                ('data_inizio', models.DateField(auto_now_add=True)),
                ('data_fine', models.DateField()),
                ('ultimo_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
