# Generated by Django 3.2.8 on 2021-10-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_permessipagine'),
        ('app', '0009_scadenziario'),
    ]

    operations = [
    ]
