# Generated by Django 3.2.8 on 2021-10-19 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0013_federazione_relutentefsn'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatoFascicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='grouplabel',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='relutentefsn',
            name='federazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.federazione'),
        ),
        migrations.AlterField(
            model_name='relutentefsn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Fascicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocollo', models.CharField(max_length=200)),
                ('anno', models.CharField(max_length=4)),
                ('progressivo', models.IntegerField(default=0)),
                ('titolo', models.TextField()),
                ('data_scadenza', models.DateField()),
                ('data_utilma_modifica', models.DateTimeField()),
                ('letto', models.BooleanField()),
                ('letto_fsn', models.BooleanField()),
                ('obbligo_visione', models.BooleanField()),
                ('prioritario', models.BooleanField()),
                ('fsn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.federazione')),
                ('stato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.statofascicolo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
