# Generated by Django 3.2.8 on 2021-10-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211019_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentobacheca',
            options={'verbose_name': 'Documento Bacheca', 'verbose_name_plural': 'Documenti Bacheca'},
        ),
        migrations.AlterModelOptions(
            name='fascicolo',
            options={'verbose_name': 'Fascicolo', 'verbose_name_plural': 'Fascicoli'},
        ),
        migrations.AlterModelOptions(
            name='federazione',
            options={'verbose_name': 'Federazione', 'verbose_name_plural': 'Federazioni'},
        ),
        migrations.AlterModelOptions(
            name='grouplabel',
            options={'verbose_name': 'Group Label', 'verbose_name_plural': 'Group Labels'},
        ),
        migrations.AlterModelOptions(
            name='permessipagine',
            options={'verbose_name': 'Permessi Pagina', 'verbose_name_plural': 'Permessi Pagine'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Persone'},
        ),
        migrations.AlterModelOptions(
            name='relutentefsn',
            options={'verbose_name': 'Relazione Utente/Federazione', 'verbose_name_plural': 'Relazioni Utenti/Federazioni'},
        ),
        migrations.AlterModelOptions(
            name='scadenziario',
            options={'verbose_name': 'Scadenzario', 'verbose_name_plural': 'Scadenzario'},
        ),
        migrations.AlterModelOptions(
            name='societa',
            options={'verbose_name': 'Società', 'verbose_name_plural': 'Società'},
        ),
        migrations.AlterModelOptions(
            name='statofascicolo',
            options={'verbose_name': 'Stato Fascicolo', 'verbose_name_plural': 'Stati Fascicoli'},
        ),
    ]
